[[nats_server]]
arch = "aarch64"
git-tree-sha1 = "578dd80241f3658ac2c69a0557f020a7fb1e7ddc"
os = "macos"

    [[nats_server.download]]
    sha256 = "2b450b9629b4e54beb6d954cc11b4d89e6a568c0de2ee64e39e84d37e02d3e86"
    url = "https://github.com/JuliaBinaryWrappers/nats_server_jll.jl/releases/download/nats_server-v2.10.18+0/nats_server.v2.10.18.aarch64-apple-darwin.tar.gz"
[[nats_server]]
arch = "aarch64"
git-tree-sha1 = "1ffc153498b6354f873a1b4573c55896be04df51"
libc = "glibc"
os = "linux"

    [[nats_server.download]]
    sha256 = "87bc1b28195a6e7c414a04247fb41d68490fac64541b31b2bcf5755654a7ab33"
    url = "https://github.com/JuliaBinaryWrappers/nats_server_jll.jl/releases/download/nats_server-v2.10.18+0/nats_server.v2.10.18.aarch64-linux-gnu.tar.gz"
[[nats_server]]
arch = "aarch64"
git-tree-sha1 = "1ffc153498b6354f873a1b4573c55896be04df51"
libc = "musl"
os = "linux"

    [[nats_server.download]]
    sha256 = "87bc1b28195a6e7c414a04247fb41d68490fac64541b31b2bcf5755654a7ab33"
    url = "https://github.com/JuliaBinaryWrappers/nats_server_jll.jl/releases/download/nats_server-v2.10.18+0/nats_server.v2.10.18.aarch64-linux-musl.tar.gz"
[[nats_server]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7b6c9333c64802246fad7486ea4b0ef9b29aed7d"
libc = "glibc"
os = "linux"

    [[nats_server.download]]
    sha256 = "17cba02d77c5105184b1b26640252ccf6eb3e44199a5704054e8784ef803238f"
    url = "https://github.com/JuliaBinaryWrappers/nats_server_jll.jl/releases/download/nats_server-v2.10.18+0/nats_server.v2.10.18.armv6l-linux-gnueabihf.tar.gz"
[[nats_server]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7b6c9333c64802246fad7486ea4b0ef9b29aed7d"
libc = "musl"
os = "linux"

    [[nats_server.download]]
    sha256 = "17cba02d77c5105184b1b26640252ccf6eb3e44199a5704054e8784ef803238f"
    url = "https://github.com/JuliaBinaryWrappers/nats_server_jll.jl/releases/download/nats_server-v2.10.18+0/nats_server.v2.10.18.armv6l-linux-musleabihf.tar.gz"
[[nats_server]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "40ffd6cd7f062a15ffb06b7a2ee5ed74e4fa42f6"
libc = "glibc"
os = "linux"

    [[nats_server.download]]
    sha256 = "1fc2bfe4b1bddb4a9b75025c5e4dde249aee6d04743ae1defd0bb66ba30b9e49"
    url = "https://github.com/JuliaBinaryWrappers/nats_server_jll.jl/releases/download/nats_server-v2.10.18+0/nats_server.v2.10.18.armv7l-linux-gnueabihf.tar.gz"
[[nats_server]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "40ffd6cd7f062a15ffb06b7a2ee5ed74e4fa42f6"
libc = "musl"
os = "linux"

    [[nats_server.download]]
    sha256 = "1fc2bfe4b1bddb4a9b75025c5e4dde249aee6d04743ae1defd0bb66ba30b9e49"
    url = "https://github.com/JuliaBinaryWrappers/nats_server_jll.jl/releases/download/nats_server-v2.10.18+0/nats_server.v2.10.18.armv7l-linux-musleabihf.tar.gz"
[[nats_server]]
arch = "i686"
git-tree-sha1 = "6f7e009608b0783f7305cfdda9dbd53124adda14"
libc = "glibc"
os = "linux"

    [[nats_server.download]]
    sha256 = "c33b00619031b93227fc302410541a534d1b4b604d6eba0db428155549239c31"
    url = "https://github.com/JuliaBinaryWrappers/nats_server_jll.jl/releases/download/nats_server-v2.10.18+0/nats_server.v2.10.18.i686-linux-gnu.tar.gz"
[[nats_server]]
arch = "i686"
git-tree-sha1 = "6f7e009608b0783f7305cfdda9dbd53124adda14"
libc = "musl"
os = "linux"

    [[nats_server.download]]
    sha256 = "c33b00619031b93227fc302410541a534d1b4b604d6eba0db428155549239c31"
    url = "https://github.com/JuliaBinaryWrappers/nats_server_jll.jl/releases/download/nats_server-v2.10.18+0/nats_server.v2.10.18.i686-linux-musl.tar.gz"
[[nats_server]]
arch = "i686"
git-tree-sha1 = "f6af5e3dce2be71b88d146e0158cdfd3fca4ee0d"
os = "windows"

    [[nats_server.download]]
    sha256 = "1e9db9c3bc74db962d55bbea271378782d9ac96911ab2ee44b35897941af0c87"
    url = "https://github.com/JuliaBinaryWrappers/nats_server_jll.jl/releases/download/nats_server-v2.10.18+0/nats_server.v2.10.18.i686-w64-mingw32.tar.gz"
[[nats_server]]
arch = "powerpc64le"
git-tree-sha1 = "bb032f3daaf584e0b9214e60dff22a7c314bbc20"
libc = "glibc"
os = "linux"

    [[nats_server.download]]
    sha256 = "a849f5529cec838322c76cb72cb2d51f1524b2725db0818501b8f087fa839e52"
    url = "https://github.com/JuliaBinaryWrappers/nats_server_jll.jl/releases/download/nats_server-v2.10.18+0/nats_server.v2.10.18.powerpc64le-linux-gnu.tar.gz"
[[nats_server]]
arch = "x86_64"
git-tree-sha1 = "05dfde0d68b81e36980de6271988bf32e9ffb22b"
os = "macos"

    [[nats_server.download]]
    sha256 = "81a4f4b06b86978670506f374752352ceb8f5f6e21f4822c10b8553673a31b8b"
    url = "https://github.com/JuliaBinaryWrappers/nats_server_jll.jl/releases/download/nats_server-v2.10.18+0/nats_server.v2.10.18.x86_64-apple-darwin.tar.gz"
[[nats_server]]
arch = "x86_64"
git-tree-sha1 = "abdacae679c9fcd88001fa19144fcc4856b794ad"
libc = "glibc"
os = "linux"

    [[nats_server.download]]
    sha256 = "64d37498dcfda81fb906bd6540e36eaa4fb81a359c7dd9a87c22faf6bac5a2fc"
    url = "https://github.com/JuliaBinaryWrappers/nats_server_jll.jl/releases/download/nats_server-v2.10.18+0/nats_server.v2.10.18.x86_64-linux-gnu.tar.gz"
[[nats_server]]
arch = "x86_64"
git-tree-sha1 = "abdacae679c9fcd88001fa19144fcc4856b794ad"
libc = "musl"
os = "linux"

    [[nats_server.download]]
    sha256 = "64d37498dcfda81fb906bd6540e36eaa4fb81a359c7dd9a87c22faf6bac5a2fc"
    url = "https://github.com/JuliaBinaryWrappers/nats_server_jll.jl/releases/download/nats_server-v2.10.18+0/nats_server.v2.10.18.x86_64-linux-musl.tar.gz"
[[nats_server]]
arch = "x86_64"
git-tree-sha1 = "7e68695bfadf4e6c460224019bb2d2ac6a62721f"
os = "freebsd"

    [[nats_server.download]]
    sha256 = "bd1426bcec8204bd01aff551f2d2eac84530beffe051e9d0c716bff15e62579e"
    url = "https://github.com/JuliaBinaryWrappers/nats_server_jll.jl/releases/download/nats_server-v2.10.18+0/nats_server.v2.10.18.x86_64-unknown-freebsd.tar.gz"
[[nats_server]]
arch = "x86_64"
git-tree-sha1 = "05b6fbd274402d6ff5bfd19c1fd998343a229cfb"
os = "windows"

    [[nats_server.download]]
    sha256 = "deb7ad413e3a55e52b7086512b752e9b891a44acfc09e02e9bd40814cd93ff84"
    url = "https://github.com/JuliaBinaryWrappers/nats_server_jll.jl/releases/download/nats_server-v2.10.18+0/nats_server.v2.10.18.x86_64-w64-mingw32.tar.gz"
